version: "2"

services:
  php:
    container_name: openloyalty_backend
    image: longhb/openloyaltymaster_backend:latest
    links:
      - db
      - elk
      - mail
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    container_name: openloyalty_frontend
    image: longhb/openloyaltymaster_frontend:latest
    links:
      - php
    ports:
      - "80:80"
      - "8182:3001"
      - "8183:3002"
      - "8184:3003"

  elk:
    container_name: openloyalty_elk
    image: elasticsearch:2.2

  db:
    container_name: open_loyalty_postgresql
    image: postgres
    environment:
      - POSTGRES_DB=openloyalty
      - POSTGRES_USER=openloyalty
      - POSTGRES_PASSWORD=openloyalty

  mail:
    container_name: open_loyalty_mail
    image: mailhog/mailhog
    ports:
      - "8186:8025"

